language: rust
sudo: false

rust:
  - nightly
  - stable

cache: cargo


addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
      - sourceline: 'deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
      - sourceline: 'deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - binutils-dev
      - libsodium-dev


before_install:
  - export ROOT_PATH=`pwd`


before_script:
  - |
    curl -sSOL https://github.com/zeromq/libzmq/releases/download/v4.2.0/zeromq-4.2.0.tar.gz
    tar zxf zeromq-4.2.0.tar.gz
    cd zeromq-4.2.0
    ./autogen.sh
    ./configure --prefix=$HOME --with-libsodium
    make && make install
    cd ..

  - export PATH=$HOME/.cargo/bin:$PATH
  - which cargo-coveralls || cargo install cargo-travis


after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo coveralls --all --verbose;
    fi