[package]
name = "eden"
version = "0.1.0"
authors = ["Alessio Coltellacci <lightplay8@gmail.com>"]

[dependencies]
slab = "0.4"
shred = "0.5"
zmq = "0.8"
log = "0.4"

[dev-dependencies]
rand = "0.4"
env_logger = "0.5"